### ISSUE TITLE
Delete Overlapping Neighbor Face operator doesn't work on Blender 2.82

### ISSUE THREAD

**Issue by Oxervision** [tkeskita/mesh_heal#1]
Hi, when you push the **Delete Overlapping Neighbor Face** button it appears this error message:

```
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/Users/Oxer/Library/Application Support/Blender/2.82/scripts/addons/mesh_heal/op_delete_overlap.py", line 44, in execute
    n = delete_overlap(context.active_object)
  File "/Users/Oxer/Library/Application Support/Blender/2.82/scripts/addons/mesh_heal/op_delete_overlap.py", line 106, in delete_overlap
    bpy.ops.mesh.print3d_clean_isolated()
  File "/Applications/Blender/BLENDER 2.80/Blender.app/Contents/Resources/2.82/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.mesh.print3d_clean_isolated" error, could not be found
```

Blender 2.82.6 & macOS 10.13.6

**Comment by tkeskita** [comment]
Hi @Oxervision ,
thanks for bug report! This issue was due to changes in Blender upstream, and I just committed a fix to mesh heal for it.
